version: '3.8'
services:    
  php-apache-environment:     
    container_name: php-apache
    image: php:8.0-apache
    volumes:        
      - .:/var/www/html/
    ports:
      - 8000:80
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: penny_wise_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - 3333:3306